Adapt docs for use with visimp-pages
visimp/visimp pull request #112
Opened 2024-09-01 15:44 UTC by foxyseta

The project can now be used as a git submodule for https://github.com/foxyseta/visimp-pages. Closes #111.

Also fixed `git.lua`(?).

2024-09-01 16:07 UTC, lucat1 requested changes

2024-09-01 16:07 UTC, lucat1 commented on _index.md
> +# `visimp`
Can't we link this file to the README?

2024-09-01 20:36 UTC, foxyseta commented on _index.md
> +# `visimp`
Hugo does not seem to work well with symlinks, while GitHub web does. I was also looking for a way to use `README.md` rather than `_index.md` in the first place, but could not find anything.

2024-09-01 22:19 UTC, lucat1 commented on _index.md
> +# `visimp`
I guess I would prefer a symlink which then gets replaced at runtime in the CI with the actual file before launching hugo.
This should work since we're dealing with just files (and I find it very cryptic which I do like)
```
sed -i '' **/*
```
(source: https://stackoverflow.com/a/12673543)

2024-09-02 05:20 UTC, foxyseta commented on _index.md
> +# `visimp`
And the symlink would be at `_index.md` and pointing to `README.md`, right?

2024-09-02 09:53 UTC, foxyseta commented on _index.md
> +# `visimp`
At this point, why not simply copying the file?

2024-09-02 21:22 UTC, lucat1 approved these changes

2024-09-02 21:22 UTC, merged